apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: priority-email-service
  namespace: priority-email
  labels:
    app.kubernetes.io/name: priority-email-service
    app.kubernetes.io/part-of: priority-email
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: priority-email-service
