apiVersion: v1
kind: ServiceAccount
metadata:
  name: priority-email-service
  namespace: priority-email
  labels:
    app.kubernetes.io/name: priority-email-service
    app.kubernetes.io/part-of: priority-email
